workspace:
  base: /go
  path: src/github.com/CloudHammer/Seeds

kind: pipeline
name: default

steps:
  - name: build
    image: golang:latest
    environment:
      GOPATH: /go
      CGO_ENABLED: '0'
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -v
      - mkdir builds
      - GOOS=linux GOARCH=amd64 go build -o builds/seeds-linux-amd64 github.com/CloudHammer/Seeds/src/main
      - GOOS=linux GOARCH=arm go build -o builds/seeds-linux-arm github.com/CloudHammer/Seeds/src/main
      - GOOS=darwin GOARCH=amd64 go build -o builds/seeds-darwin-amd64 github.com/CloudHammer/Seeds/src/main
      - GOOS=freebsd GOARCH=amd64 go build -o builds/seeds-freebsd-amd64 github.com/CloudHammer/Seeds/src/main
      - GOOS=windows GOARCH=amd64 go build -o builds/seeds-windows-amd64.exe github.com/CloudHammer/Seeds/src/main

  - name: github_release
    image: plugins/github-release
    settings:
      files:
        - builds/*
      checksum:
        - sha1
        - sha256
      when:
        event: tag
      api_key:
        from_secret: github_token

  - name: docker_release
    image: plugins/docker
    settings:
      repo: cloudhammer/seeds
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

