workspace:
  base: /go
  path: src/Seeds

pipeline:
  build:
    image: golang:latest
    environment:
      - GOPATH=/go
      - CGO_ENABLED=0
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go build -o seeds
  github_release:
    image: plugins/github-release
    files:
      - seeds
    checksum:
      - md5
      - sha1
      - sha256
    when:
      event: tag
  docker:
    image: plugins/docker
    repo: indexyz/seeds
    tags: latest
    secrets: [ docker_username, docker_password ]
  telegram:
    image: appleboy/drone-telegram
    message: >
      {{#success build.status}}
        Seeds build {{build.number}} succeeded. Good job.
      {{else}}
        Seeds build {{build.number}} failed. Fix me please.
      {{/success}}
    secrets: [ plugin_token, plugin_to ]
