workspace:
  base: /go
  path: src/github.com/CloudHammer/Seeds

kind: pipeline
name: default

pipeline:
  name: build
    image: golang:latest
    environment:
      GOPATH: /go
      CGO_ENABLED: '0'
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - mkdir builds
      - GOOS=linux GOARCH=amd64 go build -o builds/seeds-linux-amd64

  name: github_release
    image: plugins/github-release
    settings:
      files:
        - builds/*
      checksum:
        - md5
        - sha1
        - sha256
      when:
        event: tag
      api_key:
        from_secret: github_token

  # docker:
  #   image: plugins/docker
  #   repo: indexyz/seeds
  #   tags: latest
  #   secrets: [ docker_username, docker_password ]

